export const SERVICES = {
    LANDING_PAGE:'LANDING_PAGE',
    MULTI_PAGE_SITE:'MULTI_PAGE_SITE',
    INTERNET_SHOP:'INTERNET_SHOP',
    SITE_AUDIT:'SITE_AUDIT',
    INDIVIDUAL_CONSULTATION:'INDIVIDUAL_CONSULTATION',
    OTHER_SERVICES:'OTHER_SERVICES',
};